name: Translations

on:
  push:
    branches:
      - main
      - v1
      - v2

  pull_request:

permissions:
  contents: read

jobs:
  translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run prebuild

      - run: npm run sort-translations # Sort translation files

      - run: npm run check:i18n # Check for missing translations